---
switches:
  spine01:
    fabriclinks: [swp1,swp2,swp3,swp4,swp29,swp30]
    peerlinks: [swp31,swp32]
    lo:
      ipv4: 10.0.0.21/32
    bgp_as: 65020

  spine02:
    fabriclinks: [swp1,swp2,swp3,swp4,swp29,swp30]
    peerlinks: [swp31,swp32]
    lo:
      ipv4: 10.0.0.22/32
    bgp_as: 65020

  leaf01:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.11/32
      vxlan_anycast_ip: 12.12.12.12
    interfaces:
      vlan10:
        type: svi
        address: 192.168.10.1/24
        vrr_address: 192.168.10.254/24
        vrr_mac: 00:00:5e:ff:00:10
        vlan: 10
        vrf: TENANT-A
      vlan4001:
        type: svi_l3_vni
        hwaddress: 44:38:39:ff:00:12
        vlan: 4001
        vrf: TENANT-A
      vni10010:
        type: vni
        vlan: 10
        vxlan_id: 10010
      vni104001:
        type: vni
        vlan: 4001
        vxlan_id: 104001
    bridge_ports: "vni10010 vni104001 peerlink server1"
    bridge_vlans: "10 100 4001"
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:12
      clag_address: 169.254.1.1/30
      clag_peer_address: 169.254.1.2/30
      clag_priority: 1000
    bgp_as: 65011
    server:
      server_vlan: 10
      server_bond: server1
      server_interface: swp1
      server_clag_id: 1

  leaf02:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.12/32
      vxlan_anycast_ip: 12.12.12.12
    interfaces:
      vlan10:
        type: svi
        address: 192.168.10.2/24
        vrr_address: 192.168.10.254/24
        vrr_mac: 00:00:5e:ff:00:10
        vlan: 10
        vrf: TENANT-A
      vlan4001:
        type: svi_l3_vni
        hwaddress: 44:38:39:ff:00:12
        vlan: 4001
        vrf: TENANT-A
      vni10010:
        type: vni
        vlan: 10
        vxlan_id: 10010
      vni104001:
        type: vni
        vlan: 4001
        vxlan_id: 104001
    bridge_ports: "vni10010 vni104001 peerlink server1"
    bridge_vlans: "10 100 4001"
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:12
      clag_address: 169.254.1.2/30
      clag_peer_address: 169.254.1.1/30
      clag_priority: 2000
    bgp_as: 65012
    server:
      server_vlan: 10
      server_bond: server1
      server_interface: swp1
      server_clag_id: 1

  leaf03:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.13/32
      vxlan_anycast_ip: 34.34.34.34
    interfaces:
      vlan20:
        type: svi
        address: 192.168.20.3/24
        vrr_address: 192.168.20.254/24
        vrr_mac: 00:00:5e:ff:00:20
        vlan: 20
        vrf: TENANT-A
      vlan4001:
        type: svi_l3_vni
        hwaddress: 44:38:39:ff:00:33
        vlan: 4001
        vrf: TENANT-A
      vni10020:
        type: vni
        vlan: 20
        vxlan_id: 10020
      vni104001:
        type: vni
        vlan: 4001
        vxlan_id: 104001
    bridge_ports: "swp1 vni10020 vni104001"
    bridge_vlans: "20 100 4001"
    VRF:
      - TENANT-A
    bgp_as: 65013
    server:
      server_vlan: 20
      server_interface: swp1

  leaf04:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.14/32
      vxlan_anycast_ip: 34.34.34.34
    interfaces:
    bgp_as: 65014

  exit01:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.41/32
      vxlan_anycast_ip: 56.56.56.56
    interfaces:
      vlan4001:
        type: svi_l3_vni
        vlan: 4001
        hwaddress: 44:38:39:ff:00:56
        vrf: TENANT-A
      vni104001:
        type: vni
        vlan: 4001
        vxlan_id: 104001
    bridge_ports: "vni104001 peerlink"
    bridge_vlans: "4001"
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:56
      clag_address: 169.254.1.1/30
      clag_peer_address: 169.254.1.2/30
      clag_priority: 1000
    bgp_as: 65041
    bgp_peer_ip: 172.16.1.1
    internet_int_ip: 172.16.1.2/30

  exit02:
    fabriclinks: [swp51,swp52]
    peerlinks: [swp49,swp50]
    lo:
      ipv4: 10.0.0.42/32
      vxlan_anycast_ip: 56.56.56.56
    interfaces:
      vlan4001:
        type: svi_l3_vni
        vlan: 4001
        hwaddress: 44:38:39:ff:00:56
        vrf: TENANT-A
      vni104001:
        type: vni
        vlan: 4001
        vxlan_id: 104001
    bridge_ports: "vni104001 peerlink"
    bridge_vlans: "4001"
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:56
      clag_address: 169.254.1.2/30
      clag_peer_address: 169.254.1.1/30
      clag_priority: 1000
    bgp_as: 65042
    bgp_peer_ip: 172.16.2.1
    internet_int_ip: 172.16.2.2/30
