---
switches:
  spine01:
    interfaces:
      lo:
        ipv4: 10.0.0.21/32
      fabriclinks: swp1,swp2,swp3,swp4,swp29,swp30
      peerlinks: swp31,swp32
    bgp_as: 65020

  spine02:
    interfaces:
      lo:
        ipv4: 10.0.0.22/32
      fabriclinks: swp1,swp2,swp3,swp4,swp29,swp30
      peerlinks: swp31,swp32
    bgp_as: 65020

  leaf01:
    interfaces:
      lo:
        ipv4: 10.0.0.11/32
        vxlan_anycast_ip: 12.12.12.12
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      vlan_id:
        - 10
        - 100
      vxlan_id:
        - 10010
        - 10100
      svi_ip:
        - 192.168.10.1/24
        - 192.168.100.1/24
      svi_vip:
        - 192.168.10.254/24
        - 192.168.100.254/24
      svi_vmac:
        - 00:00:5e:ff:00:10
        - 00:00:5e:ff:01:00
      l3_vni_mac: 44:38:39:ff:00:12
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:12
      clag_address: 169.254.1.1/30
      clag_peer_address: 169.254.1.2/30
      clag_priority: 1000
    bgp_as: 65011
    server:
      server_vlan: 10
      server_bond: server1
      server_interface: swp1
      server_clag_id: 1

  leaf02:
    interfaces:
      lo:
        ipv4: 10.0.0.12/32
        vxlan_anycast_ip: 12.12.12.12
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      vlan_id:
        - 10
        - 100
      vxlan_id:
        - 10010
        - 10100
      svi_ip:
        - 192.168.10.2/24
        - 192.168.100.2/24
      svi_vip:
        - 192.168.10.254/24
        - 192.168.100.254/24
      svi_vmac:
        - 00:00:5e:ff:00:10
        - 00:00:5e:ff:01:00
      l3_vni_mac: 44:38:39:ff:00:12
    VRF:
      - TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:12
      clag_address: 169.254.1.2/30
      clag_peer_address: 169.254.1.1/30
      clag_priority: 2000
    bgp_as: 65012
    server:
      server_vlan: 10
      server_bond: server1
      server_interface: swp1
      server_clag_id: 1

  leaf03:
    interfaces:
      lo:
        ipv4: 10.0.0.13/32
        vxlan_anycast_ip: 34.34.34.34
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      vlan_id:
        - 20
        - 100
      vxlan_id:
        - 10020
        - 10100
      svi_ip:
        - 192.168.20.3/24
        - 192.168.100.3/24
      svi_vip:
        - 192.168.20.254/24
        - 192.168.100.254/24
      svi_vmac:
        - 00:00:5e:ff:00:20
        - 00:00:5e:ff:01:00
      l3_vni_mac: 44:38:39:ff:00:34
    VRF:
      - TENANT-A
    bgp_as: 65013
    server:
      server_vlan: 20
      server_interface: swp1

  leaf04:
    interfaces:
      lo:
        ipv4: 10.0.0.14/32
        vxlan_anycast_ip: 34.34.34.34
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      serverlinks: swp1,swp2
    bgp_as: 65014

  exit01:
    interfaces:
      lo:
        ipv4: 10.0.0.41/32
        vxlan_anycast_ip: 56.56.56.56
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      l3_vni_mac: 44:38:39:ff:00:56
      swp44_ip: 172.16.1.2/30
    VRF: TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:56
      clag_address: 169.254.1.1/30
      clag_peer_address: 169.254.1.2/30
      clag_priority: 1000
    bgp_as: 65041
    bgp_peer_ip: 172.16.1.1

  exit02:
    interfaces:
      lo:
        ipv4: 10.0.0.42/32
        vxlan_anycast_ip: 56.56.56.56
      fabriclinks: swp51,swp52
      peerlinks: swp49,swp50
      l3_vni_mac: 44:38:39:ff:00:56
      swp44_ip: 172.16.2.2/30
    VRF: TENANT-A
    clag:
      clag_sys_mac: 44:38:39:ff:00:56
      clag_address: 169.254.1.1/30
      clag_peer_address: 169.254.1.2/30
      clag_priority: 1000
    bgp_as: 65042
    bgp_peer_ip: 172.16.2.1
