---
- name: Copy server01 Interface File
  copy:
    src: files/server01_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server01"

- name: Copy server03 Interface File
  copy:
    src: files/server03_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server01"

- name: Restart Networking
  service:
    name: networking
    state: restarted








...
