---
- name: Copy server01 Interface File
  copy:
    src: files/server01_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server01"

- name: Copy server03 Interface File
  copy:
    src: files/server03_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server03"

- name: Restart Servers
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for servers to come back
  local_action: wait_for host={{ ansible_hostname }}
                state=started
  sudo: false








...
