---
- name: Copy server01 Interface File
  copy:
    src: files/server01_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server01"

- name: Copy server03 Interface File
  copy:
    src: files/server03_interfaces
    dest: /etc/network/interfaces
  when: ansible_hostname == "server03"

- name: Restart Servers
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for servers to come back
  wait_for:
    host: "{{ ansible_hostname }}"
    delay: 15








...
